USE [master]
GO

/****** Object:  Database [TESTE_VISUALSOFTWARE]    Script Date: 30/01/2022 12:22:20 ******/
CREATE DATABASE [TESTE_VISUALSOFTWARE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TESTE_VISUALSOFTWARE', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TESTE_VISUALSOFTWARE.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TESTE_VISUALSOFTWARE_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\TESTE_VISUALSOFTWARE_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TESTE_VISUALSOFTWARE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ARITHABORT OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET  MULTI_USER 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TESTE_VISUALSOFTWARE] SET  READ_WRITE 
GO

